FROM dunglas/frankenphp:1.9.1-php8.4.15-trixie AS base

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git=1:2.47.3-0+deb13u1 \
    unzip=6.0-29+deb13u1 \
    librabbitmq-dev=0.15.0-1+deb13u2 \
    supervisor=4.2.5-3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN install-php-extensions \
    pcntl \
    opcache \
    pdo \
    pdo_pgsql \
    redis \
    zip \
    intl

WORKDIR /app

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

COPY ./.docker/php/php.ini /usr/local/etc/php/php.ini

FROM base AS dev

RUN pecl install xdebug  \
    && docker-php-ext-enable xdebug

COPY ./.docker/supervisor/supervisord.dev.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

FROM base AS simple

RUN pecl install xdebug  \
    && docker-php-ext-enable xdebug

COPY ./.docker/supervisor/supervisord.simple.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

FROM base AS schedule

COPY ./.docker/supervisor/supervisord.schedule.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

FROM base AS queue

COPY ./.docker/supervisor/supervisord.queue.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

FROM base AS prod

COPY ./.docker/php/php.prod.ini /usr/local/etc/php/php.ini

COPY ./.docker/supervisor/supervisord.prod.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]